config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home', as: 'home'
  get 'static_pages/help', as: 'help'

  resources :unit_subscriptions

  get 'users/dashboard' => 'users#show', as: :user
  devise_for :users

  resources :quizzes, only:[:create, :show]

  post 'quiz/check' => 'quizzes#check'

  resources :units
  resources :vocables, only: [:create,:edit,:update, :destroy]

  post 'questions' => 'questions#create'
  get 'questions/:id' => 'questions#show'

  devise_scope :user do
  authenticated :user do
    root 'users#show', as: :authenticated_root
  end

  unauthenticated do
    root 'static_pages#home', as: :unauthenticated_root
  end
end

end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  def create
    @quiz = Quiz.create(unit_subscription_id: quiz_params[:id])

    @quiz.fetchQuestions()
    @quiz.save

    redirect_to quiz_path @quiz
  end

  def show
    @quiz = Quiz.find(params[:id])
  end

  def check
    quiz_id = check_params[:quiz_id]
    user_answers = check_params[:answers]
    if Quiz.exists?(quiz_id) and user_answers && check_params[:quest_ids]
      @question_count = user_answers.length
      @quiz = Quiz.find(quiz_id)
      unit = @quiz.unit_subscription.unit
      check_answers(user_answers, check_params[:quest_ids])
      if @quiz.unit_subscription.score
        @quiz.unit_subscription.update(score: @quiz.unit_subscription.score+  (@result / @question_count * 20).to_i)
      else
        @quiz.unit_subscription.update(score: (@result / @question_count * 20).to_i)
      end
    else
      redirect_to :unit_subscriptions
      flash[:notice] = "Internal Error"
    end
  end

  private
    def quiz_params
      params.require(:unit_subscription).permit(:id,:unit_id,:user_id)
    end

    def check_params
      params.require(:content).permit! #(:quiz_id, answers: [], quest_ids: [])
    end

    def check_answers(answers, quest_ids)
      @result = 0
      @failures = []
      answers.each do | key, user_answer|
        quest = Question.find(quest_ids[key])
        if user_answer.strip.downcase == quest.answer.downcase
          @result = @result + 1
        else
          @failures << {question: quest.question, user_answer: user_answer, right_answer: quest.answer}
        end
      end
    end

end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/quizzes/_addQuiz.html.erb
<%= form_tag('/quizzes', method: 'post', class: "form-inline ") do %>
<%= hidden_field_tag("unit_subscription[id]", unit_subscription_id) %>

<%= submit_tag("Test", class: "btn btn-success center-block") %>
<%end%>

app/views/quizzes/_form.html.erb
<%= form_tag('/quizzes', method: 'post', class: "form-inline ") do %>
<%= hidden_field_tag("unit[id]", unit_id) %>

<%= submit_tag("Test", class: "btn btn-success btn-sm") %>
<%end%>

app/views/quizzes/check.html.erb
<h2>Test Result</h2>
<p> You scored <%= @result%> / <%= @question_count %> </p>

<% if @failures.any? %>
<table class="table">
<thead>
  <th> Question:</th>
  <th> Your answer:</th>
  <th> Right answer: </th>
</thead>

  <% @failures.each do |fail|%>
  <tr>
    <td><%= fail[:question]%> </td>
    <td><%= fail[:user_answer]%> </td>
    <td> <%= fail[:right_answer] %> </td>
  </tr>
  <%end%>
</table>
<% end %>

<%= link_to 'Take another quiz for this unit', unit_subscription_path(@quiz.unit_subscription.id), class:"btn btn-default" %>
<%= link_to 'Back to my Dashboard', user_path(), class:"btn btn-default pull-right" %>

app/views/quizzes/create.html.erb
<div>
  <% @quiz.questions.each do |quest|%>
  <%= quest.question %>
  <% end %>
</div>

app/views/quizzes/show.html.erb
<div class="page-header">
<h1> Quiz for unit: <em> <%= @quiz.unit_subscription.unit.name%> </em></h1>
</div>
<%= form_tag('/quiz/check', method: 'check', class: "form-inline ") do %>

  <%= hidden_field_tag("content[quiz_id]", @quiz.id)%>
  <% quest_ids = [] %>
  <% answers = [] %>
  <% @quiz.questions.each_with_index do | quest, index|%>
    <div class="row">

      <div class="col-sm-6">
         <big> <%= quest.question  %> </big>
      </div>

      <%= hidden_field_tag("content[quest_ids][#{index}]", quest.id)%>

      <div class="col-sm-6">
        <%= text_field_tag("content[answers][#{index}]", nil, {class: "form-control"} ) %>
      </div>

    </div>
  <% end %>

  <%= submit_tag("Check the Test", class: "btn btn-success ") %>
<%end%>