config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home', as: 'home'
  get 'static_pages/help', as: 'help'

  resources :unit_subscriptions

  get 'users/dashboard' => 'users#show', as: :user
  devise_for :users

  resources :quizzes, only:[:create, :show]

  post 'quiz/check' => 'quizzes#check'

  resources :units
  resources :vocables, only: [:create,:edit,:update, :destroy]

  post 'questions' => 'questions#create'
  get 'questions/:id' => 'questions#show'

  devise_scope :user do
  authenticated :user do
    root 'users#show', as: :authenticated_root
  end

  unauthenticated do
    root 'static_pages#home', as: :unauthenticated_root
  end
end

end

app/models/unit.rb
class Unit < ActiveRecord::Base
   has_many :vocables
   has_many :unit_subscritions
   validates :name, presence: true, length: {minimum: 3}
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: [:show, :edit, :update, :destroy]
  before_action :admin_or_redirect, only: [:new, :create, :edit, :update, :destroy]

  # GET /units
  # GET /units.json
  def index
    @units = Unit.all
  end

  # GET /units/1
  # GET /units/1.json
  def show
  end

  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(unit_params)

    respond_to do |format|
      if @unit.save
        format.html { redirect_to edit_unit_path(@unit.id), notice: 'Unit was successfully created.' }
        format.json { render :show, status: :created, location: @unit }
      else
        format.html { render :new }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to @unit, notice: 'Unit was successfully updated.' }
        format.json { render :show, status: :ok, location: @unit }
      else
        format.html { render :edit }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit.destroy
    respond_to do |format|
      format.html { redirect_to units_url, notice: 'Unit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def admin_or_redirect
      unless(current_user.try(:admin?))
        flash[:alert] = "Your not allowed to access this page"
        redirect_to units_path
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:name)
    end
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_form.html.erb
<%= form_for(@unit) do |f| %>
  <% if @unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@unit.errors.count, "error") %> prohibited this unit from being saved:</h2>

      <ul>
      <% @unit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name,  class: "form-control" %>
  </div>


  <div class="actions">
    <%= f.submit 'Submit', class:"btn btn-success" %>
  </div>
<% end %>

app/views/units/_unit.html.erb
<h3>
  <%= unit.name %>
</h3>
<% if progress %>
<div class="progress">
  <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: <%= progress %>%;">
    <span class="sr-only"> <%= progress %> % Complete</span>
  </div>
</div>
<% end %>
<%= render 'vocables/vocable', vocable: unit.vocables %>

app/views/units/_vocableForm.html.erb
<%= form_tag('/vocables', method: 'post', remote: true) do %>

  <%= text_field_tag "vocable[german]" %>

  <%= text_field_tag "vocable[english]" %>

  <%= text_field_tag "vocable[swedish]" %>

  <%= hidden_field_tag("vocable[unit_id]", unit_id) %>

  <%= submit_tag("Create Vocable") %>
<%end%>

app/views/units/edit.html.erb
<h1>Editing Unit</h1>

<%= render 'form' %>



<%= render 'vocables/form', vocable: @unit.vocables, unit_id: @unit.id %>
<br>
<%= link_to 'Back', units_path, class:"btn btn-default" %>
<%= link_to 'Show', @unit, class:"btn btn-default pull-right" %>

app/views/units/index.html.erb
<h1>Select a Unit</h1>

<table class="table">
 <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
</thead>

  <tbody>
    <% @units.each do |unit| %>
      <tr>
        <td><%= link_to unit.name, unit %></td>
        <td>
          <% if user_signed_in? %>
          <%= render 'unit_subscriptions/form', unit: unit, user: current_user %>
          <% end %>
        </td>
        <% if current_user.try(:admin?)%>
        <td id="edit_link"><%= link_to 'Edit', edit_unit_path(unit) %></td>
        <td><%= link_to 'Destroy', unit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user.try(:admin?)%>
<%= link_to 'New Unit', new_unit_path, class: "btn btn-default" %>
<% end %>

app/views/units/new.html.erb
<h1>New Unit</h1>

<%= render 'form' %>




<%= link_to 'Back', units_path %>

app/views/units/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <strong>Unit:</strong>
  <%= @unit.name %>
</h1>
<%= render 'vocables/vocable', vocable: @unit.vocables %>


<%= link_to 'Back', units_path , class:"btn btn-default" %>
<% if current_user.try(:admin?) %>
<%= link_to 'Edit', edit_unit_path(@unit), class: "btn btn-default pull-right" %>
<% end %>