config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home', as: 'home'
  get 'static_pages/help', as: 'help'

  resources :unit_subscriptions

  get 'users/dashboard' => 'users#show', as: :user
  devise_for :users

  resources :quizzes, only:[:create, :show]

  post 'quiz/check' => 'quizzes#check'

  resources :units
  resources :vocables, only: [:create,:edit,:update, :destroy]

  post 'questions' => 'questions#create'
  get 'questions/:id' => 'questions#show'

  devise_scope :user do
  authenticated :user do
    root 'users#show', as: :authenticated_root
  end

  unauthenticated do
    root 'static_pages#home', as: :unauthenticated_root
  end
end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SwedishTrainer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>

  <nav class="navbar navbar-fixed-top">
    <div class="container">

      <div class="navbar-header">
        <%= link_to  "SwedishTrainer", home_path, class: "navbar-brand" %>
      </div>

    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
        <li><%= link_to  "Dashboard", user_path() %></li>
        <% end %>
        <li> <%= link_to  "Help", help_path %> </li>
      </ul>
      <p class="navbar-text navbar-right">
        <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
      </p>
    </div>

    </div>
  </nav>



<div class="container">
  <% if notice %>
  <p class="notice text-center"><%= notice %></p>
  <% end %>
  <% if alert %>
  <p class="alert text-center"><%= alert %></p>
  <%end%>
<%= yield %>
</div>
</body>
</html>